apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - target:
      kind: Ingress
      name: ingress
    path: ingress-patch.yaml

nameSuffix: -prod
namespace: neuron-prod

images:
  - name: prediction-api
    newName: lacneuronprod.azurecr.io/prediction-api
    newTag: latest
