trigger:
  batch: true
  branches:
    include:
      - main
      - release/*

variables:
  - name: python_version
    value: 3.12
  - name: poetry_version
    value: 1.7.1
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isRelease
    value: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')]

stages:
  - stage: DeployDev
    displayName: Build and deploy to Dev
    condition: eq(variables.isMain, true)
    variables:
      - group: lac-neuron-dev
      - group: lac-neuron-kv-dev
    jobs:
      - template: templates/job-deploy-train-api.yml
        parameters:
          acr_service_connection: lac-neuron-dev-acr
          env: dev
          acr_login_server: lacneurondev.azurecr.io
          service_principal_id: $(devops-sp-app-id)
          service_principal_secret: $(devops-sp-secret)
          train_api_client_id: $(TRAIN_API_CLIENT_ID)
          train_api_client_secret: $(TRAIN_API_CLIENT_SECRET)
          target_internal_storage_account_name: "lacneurondevsa"
          source_internal_storage_account_name: "lacneurondevsa"
          source_simmesh_storage_account_name: "meshlindodev"
          databricks_host: $(DATABRICKS_HOST)
          databricks_job_id: "113058821303527"
          test_url: https://training-neuron-dev.neuron-azweu-dev.vks.vestas.net
          train_api_allowed_api_keys: $(train-api-allowed-api-keys)

  - stage: DeployStaging
    displayName: Build and deploy to Staging
    condition: eq(variables.isRelease, true)
    variables:
      - group: lac-neuron-prod
      - group: lac-neuron-kv-prod
    jobs:
      - template: templates/job-deploy-train-api.yml
        parameters:
          acr_service_connection: lac-neuron-prod-acr
          env: staging
          acr_login_server: lacneuronprod.azurecr.io
          service_principal_id: $(devops-sp-app-id)
          service_principal_secret: $(devops-sp-secret)
          train_api_client_id: $(TRAIN_API_CLIENT_ID)
          train_api_client_secret: $(TRAIN_API_CLIENT_SECRET)
          target_internal_storage_account_name: "lacneuronprodsa"
          source_internal_storage_account_name: "lacneuronprodsa"
          source_simmesh_storage_account_name: "meshlindoprod"
          databricks_host: $(DATABRICKS_HOST)
          databricks_job_id: "297828316186729"
          test_url: https://training-neuron-staging.neuron-azweu-dev.vks.vestas.net
          train_api_allowed_api_keys: $(train-api-allowed-api-keys)

  - stage: DeployProd
    displayName: Build and deploy to Prod
    dependsOn: DeployStaging
    condition: and(succeeded('DeployStaging'), eq(variables.isRelease, true))
    variables:
      - group: lac-neuron-prod
      - group: lac-neuron-kv-prod
    jobs:
      - template: templates/job-approval-gate.yml
        parameters:
          deploy_environment: lac-neuron-prod-env
      - template: templates/job-deploy-train-api.yml
        parameters:
          acr_service_connection: lac-neuron-prod-acr
          env: prod
          acr_login_server: lacneuronprod.azurecr.io
          service_principal_id: $(devops-sp-app-id)
          service_principal_secret: $(devops-sp-secret)
          train_api_client_id: $(TRAIN_API_CLIENT_ID)
          train_api_client_secret: $(TRAIN_API_CLIENT_SECRET)
          target_internal_storage_account_name: "lacneuronprodsa"
          source_internal_storage_account_name: "lacneuronprodsa"
          source_simmesh_storage_account_name: "meshlindoprod"
          databricks_host: $(DATABRICKS_HOST)
          databricks_job_id: "157116723589888"
          test_url: https://training-neuron-prod.neuron-azweu-dev.vks.vestas.net
          train_api_allowed_api_keys: $(train-api-allowed-api-keys)
