alpha_significance_level: 0.05
generate_coverage_plots: False

fat_model_acceptance_criteria:
  - metric: e_mean_norm
    value: 0.01
    condition: "le"
  - metric: e_mean_norm
    value: -0.01
    condition: "ge"
  - metric: e_std_norm
    value: 0.02
    condition: "le"
    or_metric: sigma_model_form
    or_metric_value: 0.0
    or_metric_condition: "eq"

ext_model_acceptance_criteria:
  - metric: e_mean_norm
    value: 0.01
    condition: "le"
  - metric: e_mean_norm
    value: -0.01
    condition: "ge"
  - metric: e_std_norm
    value: 0.02
    condition: "le"
    or_metric: sigma_model_form
    or_metric_value: 0.0
    or_metric_condition: "eq"
